@startmindmap
* 字节码指令（202个）
** 加载和存储指令（86个）
*** load类（33个，将局部变量表中的变量加载到操作数栈）
**** iload
**** lload
**** fload
**** dload
**** aload
*** store类（33个，将栈顶的数据存储到局部变量表）
*** 常量加载（20个，根据N的范围）
**** const（15个，将常量值直接加载到操作数栈顶，【-1，5】）
**** push（2个，将常量值直接加载到操作数栈顶，bipush【-128，127】，sipush【-32768，32767】）
**** ldc（3个，从常量池加载对应的常量到操作数栈顶，N在其他范围）
** 操作数栈指令（9个）
*** pop（2个，将栈顶元素出栈）
*** dup（6个，复制栈顶元素并压入栈顶）
*** swap（1个，交换栈顶的两个元素）
** 运算和类型转换指令（57个）
*** 加法（4个，将栈顶两个元素相加并将结果压入栈顶）
*** 加法（4个，将栈顶两个元素相减并将结果压入栈顶）
*** 乘法（4个，将栈顶两个元素相乘并将结果压入栈顶）
*** 除法（4个，将栈顶两个元素相除并将结果压入栈顶）
*** 取模（4个，将栈顶两个元素取模运算并将结果压入栈顶）
*** 取负（4个，将栈顶数值取负并将结果压入栈顶）
*** 左移（2个）
*** 带符号右移（2个）
*** 无符号右移（2个）
*** 按位与（2个）
*** 按位或（2个）
*** 按位异或（2个）
*** iinc（将指定int型变量增加指定值）
*** 类型转换（15个）
*** 比较大小（5个）
** 控制转移指令（23个）
*** 条件转移（16个）
*** 复合条件转移（2个）
*** 无条件转移（5个）
** 方法调用指令（5个）
** 返回指令（6个）
** 类静态域操作（2个）
** 类实例域操作（2个）
** 锁相关（2个）
** 其他（10个）
@endmindmap