@startmindmap
* Class类文件结构
** 魔数-4字节
** 次版本号-2字节
** 主版本号-2字节
** 常量池容量计数值-2字节
** 常量池
*** 存放的数据
**** 字面量
**** 符号引用
***** 类和接口的全限定名
***** 字段的名称和描述符
***** 方法的名称和描述符
*** 常量池的项目类型
**** CONSTANT_Utf8_info（1，UTF-8编码的字符串）
***** tag-1字节
***** length-2字节
***** bytes-1字节
**** CONSTANT_Integer_info（3，整型字面量）
***** tag-1字节
***** bytes-4字节
**** CONSTANT_Float_info（4，浮点型字面量）
***** tag-1字节
***** bytes-4字节
**** CONSTANT_Long_info（5，长整型字面量）
***** tag-1字节
***** bytes-8字节
**** CONSTANT_Double_info（6，双精度浮点型字面量）
***** tag-1字节
***** bytes-8字节
**** CONSTANT_Class_info（7，类或接口的符号引用）
***** tag-1字节
***** index-2字节（指向全限定名常量项的索引）
**** CONSTANT_String_info（8，字符串类型字面量）
***** tag-1字节
***** index-2字节（指向字符串字面量的索引）
**** CONSTANT_Fieldref_info（9，字段的符号引用）
***** tag-1字节
***** index-2字节（指向声明字段的类或接口描述符的索引）
***** index-2字节（指向字段CONSTANT_NameAndType描述符的索引）
**** CONSTANT_Methodref_info（10，类中方法的符号引用）
***** tag-1字节
***** index-2字节（指向声明方法的类描述符CONSTANT_Class的索引）
***** index-2字节（指向名称及类型描述符CONSTANT_NameAndType的索引）
**** CONSTANT_InterfaceMethodref_info（11，接口中方法的符号引用）
***** tag-1字节
***** index-2字节（CONSTANT_Class）
***** index-2字节（CONSTANT_NameAndType）
**** CONSTANT_NameAndType_info（12，字段或方法的部分符号引用）
***** tag-1字节
***** index-2字节（指向该字段或方法名称常量的索引）
***** index-2字节（指向该字段或方法描述符常量的索引）
**** CONSTANT_MethodHandler_info（15，表示方法句柄）
***** tag-1字节
***** reference_kind-1字节（1-9，决定了方法句柄的类型）
***** reference-index-2字节（值必须是对常量池的有效索引）
**** CONSTANT_MethodType_info（16，标识方法类型）
***** tag-1字节
***** descriptor_index-2字节（必须是CONSTANT_Utf8_info）
**** CONSTANT_InvokeDynamic_info（18，表示一个动态方法调用点）
***** tag-1字节
***** bootstrap_method_attr_index-2字节（值必须是对当前CLass文件中引导方法表的数组的有效索引）
***** name_and_type_index-2字节（必须是CONSTANT_NameAndType_info）
** 访问标志-2字节
** 类索引-2字节
*** CONSTANT_Class_info
** 父类索引-2字节
*** CONSTANT_Class_info
** 接口计数器-2字节
** 接口索引集合
** 字段表计数器-2字节
** 字段表集合
*** access_flags-2字节
*** name_index-2字节
*** descriptor_index-2字节
*** attributes_count-2字节
*** attribute_info
** 方法表计数器-2字节
** 方法表集合
*** access_flags-2字节
*** name_index-2字节
*** descriptor_index-2字节
*** attributes_count-2字节
*** attribute_info
** 属性表计数器-2字节
** 属性表集合
*** attribute_name_index-2字节
*** attribute_length-4字节
*** info-1字节
@endmindmap