@startmindmap
* 预定义属性
** Code
*** 使用位置：方法表
*** 含义：java代码编译成的字节码指令
*** 表结构
**** attribute_name_index-2字节
**** attribute_length-4字节
**** max_stack-2字节(操作数栈深度的最大值)
**** max_locals-2字节（局部变量表所需的存储空间）
**** code_length-4字节
**** code-1字节
**** exception_table_length-2字节
**** exception_table-exception_info
**** attributes_count-2字节
**** attributes-attribute_info
** Exceptions
*** 使用位置：方法表
*** 含义：方法抛出的异常
** LineNumberTable
*** 使用位置：Code属性
*** 含义：java源码的行号与字节码指令的对应关系
** LocalVariableTable
*** 使用位置：Code属性
*** 含义：方法的局部变量描述
** SourceFile
*** 使用位置：类文件
*** 含义：记录源文件名称
** ConstantValue
*** 使用位置：字段表
*** 含义：final关键字定义的常量值
** InnerClasses
*** 使用位置：类文件
*** 含义：内部类列表
** Deprecated
*** 使用位置：类、方法表、字段表
*** 含义：被声明为Deprecated的方法和字段
** Synthetic
*** 使用位置：类、方法表、字段表
*** 含义：标识方法或字段为编译器自动生成的
** StackMapTable
*** 使用位置：Code属性
*** 含义：供新的类型检查验证器检查和处理目标方法的局部变量和操作数栈所需要的的类型是否匹配
** Signature
*** 使用位置：类、方法表、字段表
*** 含义：用于支持泛型情况下的方法签名
** BootstrapMethods
*** 使用位置：类文件
*** 含义：用于保存invokedynamic指令引用的引导方法限定符
@endmindmap