@startmindmap
* java修饰符
** 访问控制修饰符
*** default
**** 同一包内可见，可修饰：类、接口、变量、方法
*** public
*** 对所有类可见，可修饰：类、接口、变量、方法
*** private
**** 同一类内可见，可修饰：变量、方法
*** protected
**** 对同一包内的类和所有子类可见，可修饰：变量、方法
** 非访问控制修饰符
*** static
**** 修饰：类方法、类变量
*** final
**** 修饰：类、方法、变量
*** abstract
**** 修饰：类、方法
*** synchronized
**** 修饰：代码块、方法
*** volatile
**** 修饰：全局变量
*** transient
**** 修饰：全局变量
@endmindmap