@startmindmap
* Redis
** 数据类型
*** String
*** List
*** Hash
*** Set
*** Zset
*** Stream
*** Bitmap
*** HyperLogLog
*** GEO
*** 自定义数据类型
** 数据结构
*** SDS
*** dict
*** intset
*** quicklist
*** ziplist
*** adlist
** 对象编码
*** raw
*** int
*** ht
*** zipmap
*** linkedlist（新版不再使用）
*** ziplist
*** intset
*** skiplist
*** embstr
*** quicklist
*** stream
** 访问模块
*** 网络访问框架
** 缓存
*** 缓存穿透
** 持久化
*** AOF
*** RDB
** 主从库模式（只能在主库写）
** 哨兵机制（自动切换主库）
** 哨兵集群（避免单个哨兵故障以及减少误判率）
** 切片集群(保存大量数据)
@endmindmap